### ISSUE TITLE
Limited salt revision

### ISSUE THREAD

**Issue by firanto** [neoKushan/BCrypt.Net-Core#2]
I work at an environment where we use dotnet core and php (using yii2 framework). User are registered using web app built on yii2. And our new admin webapp was built using dotnet core. After tinkering a bit on your code, it seems that both are actually interoperable, but with a hurdle.

Looking at your source code, you only generate (and thus, validate) hashed password with salt revision of 'a'.

And according to [wikipedia](https://en.wikipedia.org/wiki/Bcrypt), bcrypt can use one of 'a', 'b', or 'y'. In fact, Yii2, one of well known php framework, use 'y' as salt revision. Is there any plan to make it optional instead of hardcoded as 'a'?

**Comment by neoKushan** [comment]
It looks like this is a much bigger issue than I might have realised. I'm not an expert in this area, but I will attempt to look into expanding this lib to at least support the y and revisions but I can't give a time frame on this just yet.

**Comment by firanto** [comment]
No problem. At least you are aware of the issue. Any future supports are always welcomed.

**Comment by neoKushan** [comment]
Hi @kurotsukikaitou,

Thanks for your patience with this one. I've looked into this and [dug around to see what the actual differences are between the various versions](http://stackoverflow.com/questions/15733196/where-2x-prefix-are-used-in-bcrypt). As far as I can see, _as long as your implementation was correct_, versions 2a, 2b, 2x and 2y should be identical. To my understating, 2x and 2y are not recognised as "real" versions and stem from a bug in crypt_blowfish. The 2b version came from a bug in the OpenBSD implementation and since bcrypt was originally designed for OpenBSD, they get to up the version number. The latter bug only affects passwords longer than 255 characters as well, which is going to be extremely rare.

From looking at the cause of the bugs, I'm reasonably confident that this library is correct in its implementation of bcrypt. I've made an update to it to allow it to accept hashes with 2a, 2b, 2x or 2y salt revisions - however, it treats them all the same and makes no special measures to verify an "incorrect" hash from a buggy lib. In other words, as long as yii2 is generating correct hashes, this should now be able to verify them. 

However, I can't reasonably have the lib _generate_ a hash with salt revision 2y, as that's not really part of the bcrypt spec. I have updated it to generate hashes with a salt revision of 2b as this is in line with the the latest bcrypt spec, though I'm somewhat wary that this might break things for people using older bcrypt libs. I don't know what the state for that is.

Can you test the update? It's currently a pre-release package on Nuget, you can see it here: https://www.nuget.org/packages/BCrypt.Net-Core/1.2.0-CI00004

If it's all good, I'll push this as the final release. If generating salt revision of 2b is causing issues, I'll update the lib to allow you to specify which revision you want generated (though really it'll only change the revision in the hash, it won't actually change the calculation). 

I'll leave this issue open until I get some kind of feedback on what the best approach should be. 

**If I don't hear anything back by the time VS2017 goes to RTM, I'll convert the project as-is to the new csproj format and push it as an update.**

**Comment by firanto** [comment]
I've test it. As for '2y' thing, yes, the framework did only read the 'y' so it still cause issue. So an ability to chose which revision will be great.

And you are correct, they don't actually change the calculation. Before I post this issue, I just modify your library at the input and output method to accept '2y' instead of '2a' without modifying any calculation and it already work and yii can my server can interchange the hashes without issues. So, yes, the calculation itself already correct. No need to touch it.

**Comment by neoKushan** [comment]
Okay perfect! I'll update the library to allow you to specify the revision used to fit your use case. It'll be an optional parameter so it shouldn't break existing code. Give me a couple of days to sort that out and I'll let you know here.

**Comment by neoKushan** [comment]
I found a spare hour, so @kurotsukikaitou feel free to test this revision - https://www.nuget.org/packages/BCrypt.Net-Core/1.2.0-CI00005

You should be able to pass in a SaltRevision of your choice now.

**Comment by neoKushan** [comment]
It's been over a month, so I'm going to assume this is all good. v1.3.0 final has been released and pushed to Nuget.
